name: mamba-dev
channels:
  - conda-forge/label/libsolv_dev
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake >=3.16
  - ninja
  - yaml-cpp-static
  - spdlog
  - fmt
  - libcurl
  - libcurl-static
  - xz-static
  - libssh2-static
  - libarchive-minimal-static
  - krb5-static
  - libsolv-static 0.7.24  *_6
  - zstd-static
  - libnghttp2-static
  - lz4-c-static
  - reproc-static
  - reproc-cpp
  - reproc-cpp-static
  - openssl
  - libopenssl-static
  - nlohmann_json
  - cpp-expected
