name: mamba-dev
channels:
  - conda-forge
dependencies:
  - vs2019_win-64
  - ninja
  - vcpkg
  - python
  - curl
  - cli11 >=2.2,<3
  - cpp-expected
  - cpp-filesystem
  - nlohmann_json
  - spdlog
  - fmt
  - zlib
  - winreg
  - powerloader
