name: mamba-dev
channels:
  - conda-forge
dependencies:
  - yaml-cpp-static
  # we pin an older curl build for darwin-ssl support
  - libcurl         # sel(linux)
  - libcurl-static  # sel(linux)
  - libcurl 7.76.1 *_0           # sel(osx)
  - libcurl-static  7.76.1 *_0   # sel(osx)
  - xz-static
  - libssh2-static
  - libarchive=3.3
  - krb5-static
  - libsolv-static
  - zstd-static
  - libnghttp2-static
  - lz4-c-static
  - reproc-static
  - reproc-cpp
  - reproc-cpp-static
  - openssl 1.1.1*
  - libopenssl-static 1.1.1*
  - powerloader
