name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake
  - ninja
  - nlohmann_json
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl
  - gtest
  - gmock
  - cpp-expected
  - reproc-cpp
  - yaml-cpp
  - termcolor-cpp
  - cli11 >=2.2
  - spdlog
  - sel(win): winreg
  - powerloader
