name: mamba-dev
channels:
  - conda-forge
dependencies:
  - yaml-cpp-static
  - spdlog
  - fmt
  - libcurl
  - libcurl-static
  - xz-static
  - libssh2-static
  - libarchive-minimal-static
  - krb5-static
  - libsolv-static
  - zstd-static
  - libnghttp2-static
  - lz4-c-static
  - reproc-static
  - reproc-cpp
  - reproc-cpp-static
  - openssl
  - libopenssl-static
  - powerloader-dev >=0.5.4
