name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake
  - ccache
  - ninja
  - nlohmann_json
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl 7.82.0 *_0
  - gtest
  - gmock
  - cpp-filesystem >=1.5.8
  - cpp-expected
  - reproc-cpp
  - yaml-cpp
  - termcolor-cpp
  - cli11
  - spdlog
  - pybind11
  - pytest
  - conda
  - sel(win): winreg
