name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake >=3.16
  - ninja
  - nlohmann_json
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl >=7.86
  - gtest
  - gmock
  - cpp-expected
  - reproc-cpp
  - yaml-cpp <0.8
  - cli11 >=2.2
  - spdlog
  - fmt
  - python
  - pip
  - pybind11
  - pybind11-stubgen <1.0
  - pytest >=7.3
  - pyyaml
  - conda
  - conda-content-trust
  - cryptography<40.0  # Or breaks conda-content-trust
  - pip:
    - securesystemslib
  - sel(win): winreg
