name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake
  - ninja
  - nlohmann_json
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl >=7.86
  - gtest
  - gmock
  - cpp-expected
  - reproc-cpp
  - yaml-cpp
  - cli11 >=2.2
  - spdlog
  - fmt
  - pybind11
  - pybind11-stubgen
  - pytest
  - pyyaml
  - conda
  - sel(win): winreg
  - powerloader
