name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake >=3.16
  - ninja
  - nlohmann_json
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl >=7.86
  - gtest
  - gmock
  - cpp-expected
  - reproc-cpp
  - yaml-cpp
  - cli11 >=2.2
  - spdlog
  - fmt
  - pybind11
  - pybind11-stubgen >= 2.0
  - pytest >=7.3
  - sel(win): winreg
