name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake
  - ninja
  - nlohmann_json
  - mitmproxy
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl >=7.86
  - gtest
  - gmock
  - cpp-expected
  - reproc-cpp
  - yaml-cpp
  - cli11 >=2.2
  # Pin Pytest while pytest-xprocess relies on removed features
  # https://github.com/pytest-dev/pytest-xprocess/issues/110
  - pytest <7.2.0
  - pytest-asyncio
  - pytest-lazy-fixture
  - pytest-xprocess
  - conda-package-handling
  - pyyaml
  - spdlog
  - fmt
  - sel(win): winreg
  - sel(win): pywin32
  - powerloader
