name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake
  - ninja
  - nlohmann_json
  - mitmproxy
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl 7.82.0 *_0
  - gtest
  - gmock
  - cpp-expected
  - reproc-cpp
  - yaml-cpp
  - termcolor-cpp
  - cli11 >=2.2
  - pytest
  - pytest-asyncio
  - pytest-lazy-fixture
  - pytest-xprocess
  - pyyaml
  - spdlog
  - sel(win): winreg
  - sel(win): pywin32
  - powerloader
