name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake >=3.16
  - ninja
  - nlohmann_json
  - mitmproxy
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl >=7.86
  - gtest
  - gmock
  - cpp-expected
  - reproc-cpp
  - yaml-cpp >=0.8.0
  - cli11 >=2.2
  - pytest >=7.3.0
  - pytest-asyncio
  - pytest-xprocess
  - conda-package-handling
  - requests
  - zstandard
  - pyyaml
  - spdlog
  - fmt
  - sel(win): winreg
  - sel(win): pywin32
