name: Test micro.mamba.pm

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    paths:
      - '.github/workflows/test_micro.mamba.pm.yml'
  pull_request:
    paths:
      - '.github/workflows/test_micro.mamba.pm.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_micro_mamba_pm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, shell: bash, shell-source-param: -i}
          - {os: macos-latest, shell: zsh, shell-source-param: -i}
          - {os: macos-latest, shell: bash, shell-source-param: -l}
          - {os: windows-latest, shell: bash, shell-source-param: -l}
    steps:
      - name: Install Micromamba (${{ matrix.os }}, ${{ matrix.shell }})
        run: curl -sL http://micro.mamba.pm/install.sh | ${{ matrix.shell }}
      - name: Test Micromamba
        # use either -l or -i to source .bash_profile or .bashrc/.zshrc
        run: |
          ${{ matrix.shell }} ${{ matrix.shell-source-param }} -ec micromamba
  issue:
    runs-on: ubuntu-latest
    needs: test_micro_mamba_pm
    if: failure() && github.repository_owner == 'mamba-org' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@1a16035489d05041b9af40b970f02e301c52ffba
        with:
          filename: .github/workflows/bot_issue_template.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
