name: Test micro.mamba.pm

on:
  schedule:
    - cron: '0 10 * * *'
  pull_request: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_micro_mamba_pm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        shell: [bash]
        # TODO: Fix zsh support
        # include:
        #   - {os: macos-latest, shell: zsh}
    steps:
      - name: Install Micromamba (${{ matrix.os }}, ${{ matrix.shell }})
        run: |
          # TODO: Update install.sh script for Windows
          if [ ${{ matrix.os }} = windows-latest ]; then
            mkdir -p ~/bin
            curl -Ls https://micro.mamba.pm/api/micromamba/win-64/latest \
              | bunzip2 | tar xOf - Library/bin/micromamba.exe > ~/bin/micromamba.exe
          else
            curl http://micro.mamba.pm/install.sh | ${{ matrix.shell }}
          fi
      - name: Test Micromamba
        run: ${{ matrix.shell }} -elc "micromamba --version"
      - uses: dblock/create-a-github-issue@2c9fa0d32c24d651281c37d21e5b49e333500fe8
        #if: failure()
        if: false
        with:
          filename: .github/workflows/test_issue.md
          update_existing: true
          search_existing: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
